#!/bin/bash
# sync-local-env.sh
# Syncs deployment addresses from 31337.json to API and Web .env for local dev

DEPLOYMENTS="packages/contracts/deployments/31337.json"
if [ ! -f "$DEPLOYMENTS" ]; then
    echo "⚠️  No local deployments found at $DEPLOYMENTS. Run deploy first."
    exit 1
fi

# Hardhat account #1 = AI Signer (used when AI_SIGNER not in root .env)
# Hardhat account #2 = Verifier (used when WORKPROOF_VERIFIER not in root .env)
DEFAULT_AI_SIGNER="0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
DEFAULT_VERIFIER="0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"

# Load keys from root .env if present
if [ -f ".env" ]; then
    source .env 2>/dev/null || true
fi
AI_KEY="${AI_SIGNER_PRIVATE_KEY:-$DEFAULT_AI_SIGNER}"
VERIFIER_KEY="${WORKPROOF_VERIFIER_PRIVATE_KEY:-$DEFAULT_VERIFIER}"

# Parse addresses from 31337.json
WR=$(grep -o '"WorkerRegistry": "[^"]*"' "$DEPLOYMENTS" | cut -d'"' -f4)
WP=$(grep -o '"WorkProof": "[^"]*"' "$DEPLOYMENTS" | cut -d'"' -f4)
AV=$(grep -o '"CreditAttestationVerifier": "[^"]*"' "$DEPLOYMENTS" | cut -d'"' -f4)
LV=$(grep -o '"LoanVault": "[^"]*"' "$DEPLOYMENTS" | cut -d'"' -f4)
USDC=$(grep -o '"MockUSDC": "[^"]*"' "$DEPLOYMENTS" | cut -d'"' -f4)

# Write apps/api/.env for local
mkdir -p apps/api
cat > apps/api/.env << EOF
# UnEmpower API - LOCAL DEV (auto-generated by sync-local-env.sh)
RPC_URL=http://127.0.0.1:8545
CHAIN_ID=31337

WORKER_REGISTRY_ADDRESS=$WR
WORKPROOF_ADDRESS=$WP
ATTESTATION_VERIFIER_ADDRESS=$AV
LOAN_VAULT_ADDRESS=$LV
MOCK_USDC_ADDRESS=$USDC

AI_SIGNER_PRIVATE_KEY=$AI_KEY
WORKPROOF_VERIFIER_PRIVATE_KEY=$VERIFIER_KEY

POSTGRES_URL=postgresql://unempower:unempower123@127.0.0.1:5433/unempower
DB_PORT=5433

CORS_ORIGINS=http://localhost:3000,http://localhost:3001
LOG_LEVEL=INFO
INDEXER_POLL_INTERVAL=3
INDEXER_START_BLOCK=0
DEMO_MODE=true
EOF
echo "✅ Synced apps/api/.env (local)"

# Write apps/web/.env.local for local
mkdir -p apps/web
cat > apps/web/.env.local << EOF
# UnEmpower Web - LOCAL DEV (auto-generated by sync-local-env.sh)
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_CHAIN_ID=31337

NEXT_PUBLIC_CONTRACT_WORKER_REGISTRY=$WR
NEXT_PUBLIC_CONTRACT_WORKPROOF=$WP
NEXT_PUBLIC_CONTRACT_ATTESTATION_VERIFIER=$AV
NEXT_PUBLIC_CONTRACT_LOAN_VAULT=$LV
NEXT_PUBLIC_CONTRACT_MOCK_USDC=$USDC

NEXT_PUBLIC_DEMO_ADMIN=true
EOF
echo "✅ Synced apps/web/.env.local (local)"
